name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Compile C++
      run: g++ Bataille-Navale.cpp -o Bataille
    - name: Run tests
      run: |
        ./Bataille  # Run your compiled program
